### ISSUE TITLE
BigPipe seria aplicável nesse caso?

### ISSUE THREAD

**Issue by oviniciuslara** [williankeller/BigPipe#1]
## Primeiramente venho agradecer por essa grande contribuição que é esse repositório, incrível.

Pois bem, eu estou a trabalhar em um projeto um pouco grande e pensei em colocar essa técnica em prática, porém entrei em dúvida.

Minhas páginas são tecnicamente carregadas apenas uma vez, ou seja, o css js principal são carregados na index. Nessa página existe um `view`, é nesse view que as páginas são carregadas dentro através da função `load()` do jQuery e assim funciona meu site, as páginas são puxadas e carregadas ali. Levando em conta que essas páginas não contém arquivos, apenas html comprimido.

Uso sistema de cache interno e também externo para arquivos que não se alteram com frequência como imagens etc..

Minha pergunta, seria aproveitável usar o BigPipe nesse caso, ou não faria diferença de desempenho?

**Comment by williankeller** [comment]
### Obrigado pelo contato.

Bom, a utilização do BigPipe seria uma ótima otimização de conteúdo, você sem dúvidas ganharia velocidade no carregamento dos conteúdos e das aplicações levando em conta que só o necessário será carregado.

Se você inspecionar o código fonte do facebook você vai notar que ele usar o BigPipe em cada chamada de bloco, header, footer e sidebar.
